import Head from 'next/head';
import { Parent } from '../components/Parent';
import { Child } from '../components/Child';

export default function Home() {
  return (
    <>
      <Head>
        <title>@playground/webpack-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Parent>
          <Child>ChildRight</Child>
        </Parent>
      </main>
    </>
  );
}
