name: CI

on: [push, pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install:ci

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint --ignore-pattern='/playgrounds/*'

      - name: Typecheck
        run: pnpm typecheck
